apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: morphix  
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default:6379
  - name: redisPassword
    value: "1GyY3AHsWg"
  - name: actorStateStore
    value: "true"
