// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/chat/v1/chat.proto

package chatconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/ydssx/morphix/api/chat/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "chat.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceSendMessageProcedure is the fully-qualified name of the ChatService's SendMessage RPC.
	ChatServiceSendMessageProcedure = "/chat.ChatService/SendMessage"
	// ChatServiceChatProcedure is the fully-qualified name of the ChatService's Chat RPC.
	ChatServiceChatProcedure = "/chat.ChatService/Chat"
)

// ChatServiceClient is a client for the chat.ChatService service.
type ChatServiceClient interface {
	// 客户端到服务器的流，用于发送消息
	SendMessage(context.Context) *connect_go.ClientStreamForClient[v1.ClientMessage, v1.ServerMessage]
	// 双向流，用于实现聊天
	Chat(context.Context) *connect_go.BidiStreamForClient[v1.ChatMessage, v1.ChatMessage]
}

// NewChatServiceClient constructs a client for the chat.ChatService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &chatServiceClient{
		sendMessage: connect_go.NewClient[v1.ClientMessage, v1.ServerMessage](
			httpClient,
			baseURL+ChatServiceSendMessageProcedure,
			opts...,
		),
		chat: connect_go.NewClient[v1.ChatMessage, v1.ChatMessage](
			httpClient,
			baseURL+ChatServiceChatProcedure,
			opts...,
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	sendMessage *connect_go.Client[v1.ClientMessage, v1.ServerMessage]
	chat        *connect_go.Client[v1.ChatMessage, v1.ChatMessage]
}

// SendMessage calls chat.ChatService.SendMessage.
func (c *chatServiceClient) SendMessage(ctx context.Context) *connect_go.ClientStreamForClient[v1.ClientMessage, v1.ServerMessage] {
	return c.sendMessage.CallClientStream(ctx)
}

// Chat calls chat.ChatService.Chat.
func (c *chatServiceClient) Chat(ctx context.Context) *connect_go.BidiStreamForClient[v1.ChatMessage, v1.ChatMessage] {
	return c.chat.CallBidiStream(ctx)
}

// ChatServiceHandler is an implementation of the chat.ChatService service.
type ChatServiceHandler interface {
	// 客户端到服务器的流，用于发送消息
	SendMessage(context.Context, *connect_go.ClientStream[v1.ClientMessage]) (*connect_go.Response[v1.ServerMessage], error)
	// 双向流，用于实现聊天
	Chat(context.Context, *connect_go.BidiStream[v1.ChatMessage, v1.ChatMessage]) error
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	chatServiceSendMessageHandler := connect_go.NewClientStreamHandler(
		ChatServiceSendMessageProcedure,
		svc.SendMessage,
		opts...,
	)
	chatServiceChatHandler := connect_go.NewBidiStreamHandler(
		ChatServiceChatProcedure,
		svc.Chat,
		opts...,
	)
	return "/chat.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceSendMessageProcedure:
			chatServiceSendMessageHandler.ServeHTTP(w, r)
		case ChatServiceChatProcedure:
			chatServiceChatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) SendMessage(context.Context, *connect_go.ClientStream[v1.ClientMessage]) (*connect_go.Response[v1.ServerMessage], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("chat.ChatService.SendMessage is not implemented"))
}

func (UnimplementedChatServiceHandler) Chat(context.Context, *connect_go.BidiStream[v1.ChatMessage, v1.ChatMessage]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("chat.ChatService.Chat is not implemented"))
}
