# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/event/event.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommon/event/event.proto\x12\x05\x65vent\"\xd1\x01\n\x05\x45vent\x12(\n\x07subject\x18\x01 \x01(\x0e\x32\x0e.event.SubjectR\x07subject\x12M\n\x11payment_completed\x18\x02 \x01(\x0b\x32\x1e.event.PayloadPaymentCompletedH\x00R\x10paymentCompleted\x12\x44\n\x0e\x63\x61ncel_payment\x18\x03 \x01(\x0b\x32\x1b.event.PayloadCancelPaymentH\x00R\rcancelPaymentB\t\n\x07payload\"\x8f\x01\n\x17PayloadPaymentCompleted\x12\x17\n\x07user_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n\x06\x61mount\x18\x02 \x01(\x02R\x06\x61mount\x12\x19\n\x08order_id\x18\x03 \x01(\x03R\x07orderId\x12(\n\x07subject\x18\x04 \x01(\x0e\x32\x0e.event.SubjectR\x07subject\"1\n\x14PayloadCancelPayment\x12\x19\n\x08order_id\x18\x01 \x01(\x03R\x07orderId*D\n\x07Subject\x12\x14\n\x10PaymentCompleted\x10\x00\x12\x10\n\x0cOrderCreated\x10\x01\x12\x11\n\rCancelPayment\x10\x02\x42-Z+github.com/ydssx/morphix/common/event;eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.event.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/ydssx/morphix/common/event;event'
  _globals['_SUBJECT']._serialized_start=444
  _globals['_SUBJECT']._serialized_end=512
  _globals['_EVENT']._serialized_start=36
  _globals['_EVENT']._serialized_end=245
  _globals['_PAYLOADPAYMENTCOMPLETED']._serialized_start=248
  _globals['_PAYLOADPAYMENTCOMPLETED']._serialized_end=391
  _globals['_PAYLOADCANCELPAYMENT']._serialized_start=393
  _globals['_PAYLOADCANCELPAYMENT']._serialized_end=442
# @@protoc_insertion_point(module_scope)
