// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/event/event.proto

package event

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MessageName with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageName) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageName with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageNameMultiError, or
// nil if none found.
func (m *MessageName) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageName) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContactInfo

	if len(errors) > 0 {
		return MessageNameMultiError(errors)
	}

	return nil
}

// MessageNameMultiError is an error wrapping multiple validation errors
// returned by MessageName.ValidateAll() if the designated constraints aren't met.
type MessageNameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageNameMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageNameMultiError) AllErrors() []error { return m }

// MessageNameValidationError is the validation error returned by
// MessageName.Validate if the designated constraints aren't met.
type MessageNameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageNameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageNameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageNameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageNameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageNameValidationError) ErrorName() string { return "MessageNameValidationError" }

// Error satisfies the builtin error interface
func (e MessageNameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageName.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageNameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageNameValidationError{}

// Validate checks the field values on PayloadUserCharge with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PayloadUserCharge) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayloadUserCharge with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PayloadUserChargeMultiError, or nil if none found.
func (m *PayloadUserCharge) ValidateAll() error {
	return m.validate(true)
}

func (m *PayloadUserCharge) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for OrderId

	// no validation rules for Subject

	if len(errors) > 0 {
		return PayloadUserChargeMultiError(errors)
	}

	return nil
}

// PayloadUserChargeMultiError is an error wrapping multiple validation errors
// returned by PayloadUserCharge.ValidateAll() if the designated constraints
// aren't met.
type PayloadUserChargeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayloadUserChargeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayloadUserChargeMultiError) AllErrors() []error { return m }

// PayloadUserChargeValidationError is the validation error returned by
// PayloadUserCharge.Validate if the designated constraints aren't met.
type PayloadUserChargeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayloadUserChargeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayloadUserChargeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayloadUserChargeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayloadUserChargeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayloadUserChargeValidationError) ErrorName() string {
	return "PayloadUserChargeValidationError"
}

// Error satisfies the builtin error interface
func (e PayloadUserChargeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayloadUserCharge.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayloadUserChargeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayloadUserChargeValidationError{}
