stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - make test
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - make deploy
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://morphix.com
  dependencies:
    - build
    - test