services:

  jeager:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      # - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    depends_on:
      - elasticsearch
    networks:
      - morphix_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    networks:
      - morphix_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - morphix_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    # restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - morphix_net

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - morphix_net

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: morphix
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - morphix_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./deploy/loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - morphix_net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    # volumes:
    #   - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - morphix_net

  gateway:
    image: gateway
    container_name: gateway-service
    build:
      context: ./
      dockerfile: ./app/gateway/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - etcd
      - jeager
      - user
    networks:
      - morphix_net

  user:
    image: user
    container_name: user-service
    build:
      context: ./
      dockerfile: ./app/user/Dockerfile
    depends_on:
      - etcd
      - jeager
      - sms
    networks:
      - morphix_net
    logging:
      driver: json-file

  sms:
    image: sms
    container_name: sms-service
    build:
      context: ./
      dockerfile: ./app/sms/Dockerfile
    depends_on:
      - etcd
      - jeager
    networks:
      - morphix_net

networks:
  morphix_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
