apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: morphix
build:
  local:
    concurrency: 0
    tryImportMissing: false
    useDockerCLI: false
    push: true
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_TAG}}"
  artifacts:
    - image: registry.cn-shenzhen.aliyuncs.com/ydssx/gateway
      context: .
      docker:
        dockerfile: app/gateway/Dockerfile
    - image: registry.cn-shenzhen.aliyuncs.com/ydssx/sms
      context: .
      docker:
        dockerfile: app/sms/Dockerfile
    - image: registry.cn-shenzhen.aliyuncs.com/ydssx/user
      context: .
      docker:
        dockerfile: app/user/Dockerfile
manifests:
  kustomize:
    paths:
      - deploy\kubernetes\svc
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["cmd.exe", "/C", "kubectl label namespace morphix istio-injection=enabled --overwrite"]
            os: [windows]
        - host:
            command: ["sh", "-c", "kubectl label namespace morphix istio-injection=enabled --overwrite"]
            os: [darwin, linux]
