"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GenerateStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenerateStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GenerateStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PENDING: _GenerateStatus.ValueType  # 0
    """待处理"""
    RUNNING: _GenerateStatus.ValueType  # 1
    """处理中"""
    COMPLETED: _GenerateStatus.ValueType  # 2
    """处理完成"""
    FAILED: _GenerateStatus.ValueType  # 3
    """处理失败"""
    CANCELED: _GenerateStatus.ValueType  # 4
    """处理取消"""
    TIMEOUT: _GenerateStatus.ValueType  # 5
    """处理超时"""
    UNKNOWN: _GenerateStatus.ValueType  # 6
    """未知状态"""

class GenerateStatus(_GenerateStatus, metaclass=_GenerateStatusEnumTypeWrapper): ...

PENDING: GenerateStatus.ValueType  # 0
"""待处理"""
RUNNING: GenerateStatus.ValueType  # 1
"""处理中"""
COMPLETED: GenerateStatus.ValueType  # 2
"""处理完成"""
FAILED: GenerateStatus.ValueType  # 3
"""处理失败"""
CANCELED: GenerateStatus.ValueType  # 4
"""处理取消"""
TIMEOUT: GenerateStatus.ValueType  # 5
"""处理超时"""
UNKNOWN: GenerateStatus.ValueType  # 6
"""未知状态"""
global___GenerateStatus = GenerateStatus

@typing_extensions.final
class GenerateImageRequest(google.protobuf.message.Message):
    """图像生成请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ImageGenerationMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ImageGenerationModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GenerateImageRequest._ImageGenerationMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        GENERATE_MODE_DEFAULT: GenerateImageRequest._ImageGenerationMode.ValueType  # 0
        """默认模式"""
        GENERATE_MODE_GUIDANCE: GenerateImageRequest._ImageGenerationMode.ValueType  # 1
        """指导模式"""

    class ImageGenerationMode(_ImageGenerationMode, metaclass=_ImageGenerationModeEnumTypeWrapper): ...
    GENERATE_MODE_DEFAULT: GenerateImageRequest.ImageGenerationMode.ValueType  # 0
    """默认模式"""
    GENERATE_MODE_GUIDANCE: GenerateImageRequest.ImageGenerationMode.ValueType  # 1
    """指导模式"""

    @typing_extensions.final
    class GenerationParameters(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODEL_NAME_FIELD_NUMBER: builtins.int
        SAMPLING_STEPS_FIELD_NUMBER: builtins.int
        SAMPLING_METHOD_FIELD_NUMBER: builtins.int
        model_name: builtins.str
        """模型名称"""
        sampling_steps: builtins.int
        """采样步数"""
        sampling_method: builtins.str
        """采样方法"""
        def __init__(
            self,
            *,
            model_name: builtins.str = ...,
            sampling_steps: builtins.int = ...,
            sampling_method: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["model_name", b"model_name", "sampling_method", b"sampling_method", "sampling_steps", b"sampling_steps"]) -> None: ...

    @typing_extensions.final
    class GuidanceParameters(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PROMPT_FIELD_NUMBER: builtins.int
        GUIDANCE_SCALE_FIELD_NUMBER: builtins.int
        prompt: builtins.str
        """指导文本"""
        guidance_scale: builtins.float
        """指导尺度"""
        def __init__(
            self,
            *,
            prompt: builtins.str = ...,
            guidance_scale: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["guidance_scale", b"guidance_scale", "prompt", b"prompt"]) -> None: ...

    ORIGINAL_IMAGE_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    IMAGE_SIZE_FIELD_NUMBER: builtins.int
    GUIDANCE_SCALE_FIELD_NUMBER: builtins.int
    GENERATION_PARAMETERS_FIELD_NUMBER: builtins.int
    IMAGE_GENERATION_MODE_FIELD_NUMBER: builtins.int
    original_image: builtins.bytes
    """原始图像数据"""
    prompt: builtins.str
    """生成提示文本"""
    image_size: builtins.int
    """图像大小"""
    guidance_scale: builtins.float
    """指导尺度"""
    @property
    def generation_parameters(self) -> global___GenerateImageRequest.GenerationParameters:
        """其他生成参数"""
    image_generation_mode: global___GenerateImageRequest.ImageGenerationMode.ValueType
    """图像生成模式"""
    def __init__(
        self,
        *,
        original_image: builtins.bytes = ...,
        prompt: builtins.str = ...,
        image_size: builtins.int = ...,
        guidance_scale: builtins.float = ...,
        generation_parameters: global___GenerateImageRequest.GenerationParameters | None = ...,
        image_generation_mode: global___GenerateImageRequest.ImageGenerationMode.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["generation_parameters", b"generation_parameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["generation_parameters", b"generation_parameters", "guidance_scale", b"guidance_scale", "image_generation_mode", b"image_generation_mode", "image_size", b"image_size", "original_image", b"original_image", "prompt", b"prompt"]) -> None: ...

global___GenerateImageRequest = GenerateImageRequest

@typing_extensions.final
class GenerateImageResponse(google.protobuf.message.Message):
    """图像生成响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_ID_FIELD_NUMBER: builtins.int
    image_id: builtins.str
    """生成的图像ID"""
    def __init__(
        self,
        *,
        image_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_id", b"image_id"]) -> None: ...

global___GenerateImageResponse = GenerateImageResponse

@typing_extensions.final
class GenerationParameters(google.protobuf.message.Message):
    """生成参数"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_NAME_FIELD_NUMBER: builtins.int
    SAMPLING_STEPS_FIELD_NUMBER: builtins.int
    SAMPLING_METHOD_FIELD_NUMBER: builtins.int
    model_name: builtins.str
    """模型名称"""
    sampling_steps: builtins.int
    """采样步数"""
    sampling_method: builtins.str
    """采样方法"""
    def __init__(
        self,
        *,
        model_name: builtins.str = ...,
        sampling_steps: builtins.int = ...,
        sampling_method: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_name", b"model_name", "sampling_method", b"sampling_method", "sampling_steps", b"sampling_steps"]) -> None: ...

global___GenerationParameters = GenerationParameters

@typing_extensions.final
class GetGenerateStatusRequest(google.protobuf.message.Message):
    """获取生成状态请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_ID_FIELD_NUMBER: builtins.int
    image_id: builtins.str
    def __init__(
        self,
        *,
        image_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_id", b"image_id"]) -> None: ...

global___GetGenerateStatusRequest = GetGenerateStatusRequest

@typing_extensions.final
class GenerateStatusResponse(google.protobuf.message.Message):
    """生成状态响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___GenerateStatus.ValueType
    def __init__(
        self,
        *,
        status: global___GenerateStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["status", b"status"]) -> None: ...

global___GenerateStatusResponse = GenerateStatusResponse

@typing_extensions.final
class GetGeneratedImageRequest(google.protobuf.message.Message):
    """获取生成图像请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_ID_FIELD_NUMBER: builtins.int
    image_id: builtins.str
    def __init__(
        self,
        *,
        image_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_id", b"image_id"]) -> None: ...

global___GetGeneratedImageRequest = GetGeneratedImageRequest

@typing_extensions.final
class GetGeneratedImageResponse(google.protobuf.message.Message):
    """获取生成图像响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_data", b"image_data"]) -> None: ...

global___GetGeneratedImageResponse = GetGeneratedImageResponse

@typing_extensions.final
class GetModelInfoResponse(google.protobuf.message.Message):
    """模型信息响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_NAME_FIELD_NUMBER: builtins.int
    MODEL_VERSION_FIELD_NUMBER: builtins.int
    model_name: builtins.str
    """模型名称"""
    model_version: builtins.str
    """模型版本"""
    def __init__(
        self,
        *,
        model_name: builtins.str = ...,
        model_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_name", b"model_name", "model_version", b"model_version"]) -> None: ...

global___GetModelInfoResponse = GetModelInfoResponse

@typing_extensions.final
class ImageToImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORIGINAL_IMAGE_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    IMAGE_SIZE_FIELD_NUMBER: builtins.int
    GUIDANCE_SCALE_FIELD_NUMBER: builtins.int
    SAMPLING_STEPS_FIELD_NUMBER: builtins.int
    SAMPLING_METHOD_FIELD_NUMBER: builtins.int
    original_image: builtins.bytes
    """原始图像数据"""
    prompt: builtins.str
    """生成提示文本"""
    image_size: builtins.int
    """图像大小"""
    guidance_scale: builtins.float
    """指导尺度"""
    sampling_steps: builtins.int
    """采样步数"""
    sampling_method: builtins.str
    """采样方法"""
    def __init__(
        self,
        *,
        original_image: builtins.bytes = ...,
        prompt: builtins.str = ...,
        image_size: builtins.int = ...,
        guidance_scale: builtins.float = ...,
        sampling_steps: builtins.int = ...,
        sampling_method: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["guidance_scale", b"guidance_scale", "image_size", b"image_size", "original_image", b"original_image", "prompt", b"prompt", "sampling_method", b"sampling_method", "sampling_steps", b"sampling_steps"]) -> None: ...

global___ImageToImageRequest = ImageToImageRequest

@typing_extensions.final
class ImageToImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_ID_FIELD_NUMBER: builtins.int
    image_id: builtins.str
    """生成的图像ID"""
    def __init__(
        self,
        *,
        image_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_id", b"image_id"]) -> None: ...

global___ImageToImageResponse = ImageToImageResponse
