// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ydssx/morphix/app/sms/internal/biz"
	"github.com/ydssx/morphix/app/sms/internal/server"
	"github.com/ydssx/morphix/app/sms/internal/service"
	"github.com/ydssx/morphix/common/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	client, err := biz.NewSmsRedisClient(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	smsUseCase := biz.NewSmsUseCase(client)
	smsService := service.NewSMSService(smsUseCase)
	httpServer := server.NewHTTPServer(bootstrap, smsService)
	grpcServer := server.NewGRPCServer(bootstrap, smsService)
	v, err := server.NewServer(httpServer, grpcServer, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(bootstrap, v...)
	return app, func() {
	}, nil
}
