etcd:
  endpoints:
    - etcd.default:2379
  timeout: 5
  username: root
  password: YV2AsfxOTo

jaeger:
  addr: http://jaeger:14268/api/traces

otelcol:
  addr: otelcol:4317

nats:
  addr: nats://nats.default:4222
  timeout: 5

userRpcClient:
  network: tcp
  addr: discovery:///user-rpc
  timeout: 2

smsRpcClient:
  network: tcp
  addr: discovery:///sms-rpc
  timeout: 2

paymentRpcClient:
  network: tcp
  addr: discovery:///payment-rpc
  timeout: 2

orderRpcClient:
  network: tcp
  addr: discovery:///order-rpc
  timeout: 2

# gateway配置
gateway:
  name: gateway
  addr: 0.0.0.0:8000

# user服务配置
user:
  name: user-rpc
  server:
    grpc:
      addr: 0.0.0.0:9000
      timeout: 2
  data:
    database:
      driver: mysql
      source: root:root@tcp(mysql.default:3306)/user
    redis:
      addr: redis-master.default:6379
      username:
      password: 1GyY3AHsWg
      read_timeout: 2
      write_timeout: 2
      dial_timeout: 5

# sms服务配置
sms:
  name: sms-rpc
  server:
    grpc:
      addr: 0.0.0.0:9001
      timeout: 2
  data:
    database:
      driver: mysql
      source: root:root@tcp(mysql.default:3306)/sms
    redis:
      addr: redis-master.default:6379
      username:
      password: 1GyY3AHsWg
      read_timeout: 2
      write_timeout: 2
      dial_timeout: 5

# payment服务配置
payment:
  name: payment-rpc
  server:
    grpc:
      addr: 0.0.0.0:9002
      timeout: 2
  data:
    database:
      driver: mysql
      source: root:root@tcp(mysql.default:3306)/payment
    redis:
      addr: redis-master.default:6379
      username:
      password: 1GyY3AHsWg
      read_timeout: 2
      write_timeout: 2
      dial_timeout: 5

# order服务配置
order:
  name: order-rpc
  server:
    grpc:
      addr: 0.0.0.0:9003
      timeout: 2
  data:
    database:
      driver: mysql
      source: root:root@tcp(mysql.default:3306)/order
    redis:
      addr: redis-master.default:6379
      username:
      password: 1GyY3AHsWg
      read_timeout: 2
      write_timeout: 2
      dial_timeout: 5
