apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        dapr.io/enabled: "true"
        dapr.io/app-id: "gateway"
        dapr.io/app-port: "8000"
        dapr.io/app-protocol: "http"
    spec:
      containers:
        - name: gateway
          image: registry.cn-shenzhen.aliyuncs.com/ydssx/gateway:1.0.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/morphix
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: config-volume
          configMap:
            name: morphix-config

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
