configMapGenerator:
  - name: morphix-config
    files:
      - config.yaml
    namespace: morphix
resources:
  - gateway-svc.yaml
  - sms-svc.yaml
  - user-svc.yaml
  - payment-svc.yaml
  - order-svc.yaml
  - job-svc.yaml
  - secret.yaml
generatorOptions:
  disableNameSuffixHash: true
namespace: morphix
commonLabels:
  project: morphix

images:
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/gateway
    newTag: 1.0.4
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/job
    newTag: 1.0.4
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/order
    newTag: 1.0.4
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/payment
    newTag: 1.0.4
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/sms
    newTag: 1.0.4
  - name: registry.cn-shenzhen.aliyuncs.com/ydssx/user
    newTag: 1.0.4
