apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        # sidecar.istio.io/inject: "false"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: order-service
          image: registry.cn-shenzhen.aliyuncs.com/ydssx/order:1.0.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          ports:
            - containerPort: 9003
          volumeMounts:
            - name: config-volume
              mountPath: /etc/morphix
          livenessProbe:
            grpc:
              port: 9003
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: config-volume
          configMap:
            name: morphix-config

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: ClusterIP
  ports:
    - name: order-service
      port: 9003
      targetPort: 9003
      protocol: TCP
