apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        # sidecar.istio.io/inject: "false"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        dapr.io/enabled: "true"
        dapr.io/app-id: "payment"
        dapr.io/app-port: "9002"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: payment
          image: registry.cn-shenzhen.aliyuncs.com/ydssx/payment:1.0.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          ports:
            - containerPort: 9002
          volumeMounts:
            - name: config-volume
              mountPath: /etc/morphix
          livenessProbe:
            grpc:
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: TZ
              value: "Asia/Shanghai"
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: config-volume
          configMap:
            name: morphix-config

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: ClusterIP
  ports:
    - name: payment-service
      port: 9002
      targetPort: 9002
      protocol: TCP
