apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: morphix
spec:
  encryptedData:
    HUGGINGFACE_TOKEN: AgBhjEwhtCnphvi3m1cpLRJwlZR6IBO9YiGUOJH3RdIJmTu1yVgoAG2ydpTRRvrGcyOiOumlrLeH98iXncxzlexR8bomXiH58yntatNvgQETWh7FBHV94LPJ5dKipVPRds5bE79c0h/1xCer3GVBZe2/9nJvZ21FWrRIwMMDODCEo47ms2heUFUP0LV8M0Okqk3bcr7+65WQtws5lM5yWW/rnIGRDEUehuJCOzECzCXAghzk8DXKUO5uNdConmNPFvUybwN9rYUkF3ZP+EsM3TQMKDixx2xx0T/7kw0T9Q2Y4zilDMVESUdaV3MtbYJSZ8QSemqwVq7ZaODPkALXWHN3qR4bWiET9uNIbOkbK1nFfwLLHEVvSEgKpiySdPBYeQXxxDFh3yEJyVi6wAclxdlT/Lpkp6arTjdMjJEmYdRGt4upSi0+GqYMVsFZnPuFiTLZqIDWkiKtr7CFPM3QMAZP4Qn6cbIeah2driYz2AtXd28VD7F4pTSfVN4nEKKoNJTW0Vzu45yQWsAPatUa/W/hg32hquV5wvQdvKcIuGKbO4c36QoaXO15VDUpgOVTTYTHsz+tHkmhZpq4Jej3ixJFVfvwa/LBZ2h8jifL+vEFeZmdtzM1247RxSIT2b6L9DiTlv9dghGfdaIFqv4aEgRb64rb6mQK2HNdPQ71KQhYAmLpdlAhZPijk/mKLlrQSPhYCPKYRM8xoGXIVJNQ9U4w6hSTsK9UpFKd1tJYsyFU5ElIabmx
    REDIS_PASSWORD: AgBM8qTCPuC+OPTX11ysFupMWLym2QEoSVDhhAqvUlVFdXUcOyrzJOnwQBSJZWGcWoxd+c6fmFVczD/WEbYR9Ug1h5UiyMpTk8PA4mXm3JIceNwMdHbfgguc5cP+9ON3h2kLvWYlN1n5se8fJh/uzmkNGzsa65EePuVzG6DR2qll0wvJTht3/DOWVE3tpwod9poCZWwVeHO/vF5a5xyJUlOWs7pBlEL6jNFUAyoQdAVAmZ4dLs95TcmIaVOU9IFLeI+KTkYfPZhIzkrALvF45MimLainfHqw12IxYlceja1vO1K3Zg/jUwBwmABHaTBJ705eSmEve6UII/Wi7iEPALZ14OpG3ANZ5mo+xakFoH4funwCHpZBUiyNSV5r4kEls+mslvVsz0UWt4X9Kq/P9KCGnH5UPBhsoX+4hyXZTotmDl9OKPM/Pms/Fp7UxghkoDNIwMly6DiFum9tG0ZMFt7bv8GEoC1j6J6YK8onZ/Ozfaom/d/eQP4YGiJG/nTtXrUdpmrzUyMyG4idD8gVZociImfhwsnr6m7Zu1b4keokduZ0XH1BpD6Ru8OwAANydqYKfzoYBI+sj63pp4ASpH/OBuD86yf20XLqAASw4eTcBD72n2kjZn4v7ubZDTJNrhVQXVb7AFv6hFzRiCqbNouxOiRIOXJOGqviuq1R8wC9XqgG8d/Z6BxXmPKyaW3B9ShLVWUvs/B3yJIt
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: morphix
    type: Opaque
---
