apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms
  labels:
    app: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        dapr.io/enabled: "true"
        dapr.io/app-id: "sms"
        dapr.io/app-port: "9001"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: sms
          image: registry.cn-shenzhen.aliyuncs.com/ydssx/sms:1.0.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: config-volume
              mountPath: /etc/morphix
          livenessProbe:
            grpc:
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
            - name: TZ
              value: "Asia/Shanghai"
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: config-volume
          configMap:
            name: morphix-config

---
apiVersion: v1
kind: Service
metadata:
  name: sms-service
spec:
  selector:
    app: sms-service
  type: ClusterIP
  ports:
    - name: sms
      port: 9001
      targetPort: 9001
      protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sms-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sms
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
