apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  labels:
    app: sms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
        - name: sms-service
          image: registry.cn-shenzhen.aliyuncs.com/ydssx/sms:1.0.2
          imagePullPolicy: Always
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: config-volume
              mountPath: /etc/morphix
          livenessProbe:
            grpc:
              port: 9001
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: aliyun-registry-secret
      volumes:
        - name: config-volume
          configMap:
            name: morphix-config

---
apiVersion: v1
kind: Service
metadata:
  name: sms-service
spec:
  selector:
    app: sms-service
  type: ClusterIP
  ports:
    - name: sms-service
      port: 9001
      targetPort: 9001
      protocol: TCP
