global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: gateway_server
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: etcd
    static_configs:
      - targets: ["etcd:2379"]