etcd:
  endpoints:
    - 127.0.0.1:2379
  timeout: 5s
  username: root
  password: YV2AsfxOTo

jaeger:
  addr: http://jaeger:14268/api/traces

otelcol:
  addr: 127.0.0.1:4317

nats:
  addr: nats://127.0.0.1:4222
  timeout: 5s

redisCluster:
  addr:
    - redis-master.default:6379
    - redis-replicas.default:6379
  username:
  password: 1GyY3AHsWg
  read_timeout: 2s
  write_timeout: 2s
  dial_timeout: 5s

redis:
  addr: 127.0.0.1:6379
  username:
  password: 1GyY3AHsWg
  read_timeout: 2s
  write_timeout: 2s
  dial_timeout: 5s

# 客户端配置
clientSet:
  userRpcClient:
    network: tcp
    addr: discovery:///user-rpc
    timeout: 2s

  smsRpcClient:
    network: tcp
    addr: discovery:///sms-rpc
    timeout: 2s

  paymentRpcClient:
    network: tcp
    addr: discovery:///payment-rpc
    timeout: 2s

  orderRpcClient:
    network: tcp
    addr: discovery:///order-rpc
    timeout: 2s

  jobRpcClient:
    network: tcp
    addr: discovery:///job-rpc
    timeout: 2s
  
  quoteRpcClient:
    network: tcp
    addr: discovery:///quote-rpc
    timeout: 2s

serviceSet:
  # gateway配置
  gateway:
    name: gateway
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 2s

  # user服务配置
  user:
    name: user-rpc
    server:
      grpc:
        addr: 0.0.0.0:9000
        timeout: 2s
      http:
        addr: 0.0.0.0:9001
        timeout: 2s
    data:
      database:
        driver: mysql
        source: root:root@tcp(localhost:3307)/user?parseTime=true&loc=Local
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s
      mongo:
        addr: mongodb://root:RSeMAN7csL@127.0.0.1:27017
        username: root
        password: RSeMAN7csL
        database: user
        collection: user
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s


  # sms服务配置
  sms:
    name: sms-rpc
    enableRegistry: false
    enableTracing: false
    server:
      grpc:
        addr: 0.0.0.0:9001
        timeout: 2s
      http:
        addr: 0.0.0.0:9002
        timeout: 2s
    data:
      database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:3306)/sms?parseTime=true&loc=Local
      redis:
        addr: localhost:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s

  # payment服务配置
  payment:
    name: payment-rpc
    server:
      grpc:
        addr: 0.0.0.0:9002
        timeout: 2s
    data:
      database:
        driver: mysql
        source: root:root@tcp(mysql.default:3306)/payment?parseTime=true&loc=Local
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s

  # order服务配置
  order:
    name: order-rpc
    enableRegistry: false
    enableTracing: false
    server:
      grpc:
        addr: 0.0.0.0:9003
        timeout: 2s
      http:
        addr: 0.0.0.0:9004
        timeout: 2s
    data:
      database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:3306)/order?parseTime=true&loc=Local
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s

  # job服务配置
  job:
    name: job-rpc
    server:
      grpc:
        addr: 0.0.0.0:9004
        timeout: 2s
    data:
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s
  aiart:
    name: aiart-rpc
    enableRegistry: false
    enableTracing: false
    enableMetric: false
    server:
      grpc:
        addr: 0.0.0.0:9005
        timeout: 5s
        disabled: true
      http:
        addr: 0.0.0.0:9006
        timeout: 2s
        disabled: false
    data:
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s

  quote:
    name: quote-rpc
    enableMetric: false
    enableTracing: false
    server:
      grpc:
        addr: 0.0.0.0:9007
        timeout: 2s
      http:
        addr: 0.0.0.0:9008
        timeout: 2s
        disabled: true
    data:
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
        dial_timeout: 5s
  product:
    name: product-rpc
    enableRegistry: true
    enableTracing: false
    enableMetric: false
    server:
      grpc:
        addr: 0.0.0.0:9009
        timeout: 2s
      http:
        addr: 0.0.0.0:9010
        timeout: 2s
        disabled: true
    data:
      redis:
        addr: 127.0.0.1:6379
        username:
        password: 1GyY3AHsWg
        read_timeout: 2s
        write_timeout: 2s
      database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:3307)/product?parseTime=true&loc=Local
