# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/job/v1/job.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/job/v1/job.proto\x12\x06job.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n\x0e\x45nqueueRequest\x12*\n\x08job_type\x18\x01 \x01(\x0e\x32\x0f.job.v1.JobTypeR\x07jobType\x12\x18\n\x07payload\x18\x02 \x01(\x0cR\x07payload\x12\x1d\n\nretry_time\x18\x03 \x01(\x03R\tretryTime\x12\x39\n\nprocess_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tprocessAt\x12\x38\n\nprocess_in\x18\x05 \x01(\x0b\x32\x19.google.protobuf.DurationR\tprocessIn\x12\x36\n\x08\x64\x65\x61\x64line\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08\x64\x65\x61\x64line\x12\x37\n\tretention\x18\x07 \x01(\x0b\x32\x19.google.protobuf.DurationR\tretention\"*\n\x0f\x45nqueueResponse\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\".\n\x11QueryTasksRequest\x12\x19\n\x08task_ids\x18\x01 \x03(\tR\x07taskIds\"\xa4\x01\n\x12QueryTasksResponse\x12\x39\n\x05tasks\x18\x01 \x03(\x0b\x32#.job.v1.QueryTasksResponse.TaskInfoR\x05tasks\x1aS\n\x08TaskInfo\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n\x06result\x18\x02 \x01(\x0cR\x06result\x12\x16\n\x06status\x18\x03 \x01(\tR\x06status\"\x1f\n\x0bPayLoadTest\x12\x10\n\x03msg\x18\x01 \x01(\tR\x03msg\"9\n\x1cPayLoadOrderPaymentCompleted\x12\x19\n\x08order_id\x18\x01 \x01(\x03R\x07orderId\"2\n\x13PayLoadOrderTimeout\x12\x1b\n\torder_num\x18\x01 \x01(\tR\x08orderNum*Z\n\x07JobType\x12\x0c\n\x08TEST_JOB\x10\x00\x12\x11\n\rTEST_CRON_JOB\x10\x01\x12\x1b\n\x17ORDER_PAYMENT_COMPLETED\x10\x02\x12\x11\n\rORDER_TIMEOUT\x10\x03\x32\xa7\x01\n\nJobService\x12:\n\x07\x45nqueue\x12\x16.job.v1.EnqueueRequest\x1a\x17.job.v1.EnqueueResponse\x12]\n\nQueryTasks\x12\x19.job.v1.QueryTasksRequest\x1a\x1a.job.v1.QueryTasksResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/tasks/queryB+Z)github.com/ydssx/morphix/api/job/v1;jobv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.job.v1.job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/ydssx/morphix/api/job/v1;jobv1'
  _globals['_JOBSERVICE'].methods_by_name['QueryTasks']._loaded_options = None
  _globals['_JOBSERVICE'].methods_by_name['QueryTasks']._serialized_options = b'\202\323\344\223\002\022\022\020/api/tasks/query'
  _globals['_JOBTYPE']._serialized_start=909
  _globals['_JOBTYPE']._serialized_end=999
  _globals['_ENQUEUEREQUEST']._serialized_start=157
  _globals['_ENQUEUEREQUEST']._serialized_end=504
  _globals['_ENQUEUERESPONSE']._serialized_start=506
  _globals['_ENQUEUERESPONSE']._serialized_end=548
  _globals['_QUERYTASKSREQUEST']._serialized_start=550
  _globals['_QUERYTASKSREQUEST']._serialized_end=596
  _globals['_QUERYTASKSRESPONSE']._serialized_start=599
  _globals['_QUERYTASKSRESPONSE']._serialized_end=763
  _globals['_QUERYTASKSRESPONSE_TASKINFO']._serialized_start=680
  _globals['_QUERYTASKSRESPONSE_TASKINFO']._serialized_end=763
  _globals['_PAYLOADTEST']._serialized_start=765
  _globals['_PAYLOADTEST']._serialized_end=796
  _globals['_PAYLOADORDERPAYMENTCOMPLETED']._serialized_start=798
  _globals['_PAYLOADORDERPAYMENTCOMPLETED']._serialized_end=855
  _globals['_PAYLOADORDERTIMEOUT']._serialized_start=857
  _globals['_PAYLOADORDERTIMEOUT']._serialized_end=907
  _globals['_JOBSERVICE']._serialized_start=1002
  _globals['_JOBSERVICE']._serialized_end=1169
# @@protoc_insertion_point(module_scope)
