"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class VideoUploadRequest(google.protobuf.message.Message):
    """视频上传请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEODATA_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    videoData: builtins.bytes
    filename: builtins.str
    """其他字段..."""
    def __init__(
        self,
        *,
        videoData: builtins.bytes = ...,
        filename: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filename", b"filename", "videoData", b"videoData"]) -> None: ...

global___VideoUploadRequest = VideoUploadRequest

@typing_extensions.final
class VideoUploadResponse(google.protobuf.message.Message):
    """视频上传响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEOID_FIELD_NUMBER: builtins.int
    videoId: builtins.str
    """其他字段..."""
    def __init__(
        self,
        *,
        videoId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["videoId", b"videoId"]) -> None: ...

global___VideoUploadResponse = VideoUploadResponse

@typing_extensions.final
class VideoTranscodeRequest(google.protobuf.message.Message):
    """视频转码请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEOID_FIELD_NUMBER: builtins.int
    OUTPUTFORMATS_FIELD_NUMBER: builtins.int
    videoId: builtins.str
    @property
    def outputFormats(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """其他字段..."""
    def __init__(
        self,
        *,
        videoId: builtins.str = ...,
        outputFormats: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["outputFormats", b"outputFormats", "videoId", b"videoId"]) -> None: ...

global___VideoTranscodeRequest = VideoTranscodeRequest

@typing_extensions.final
class VideoTranscodeResponse(google.protobuf.message.Message):
    """视频转码响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSCODEDVIDEOIDS_FIELD_NUMBER: builtins.int
    @property
    def transcodedVideoIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """其他字段..."""
    def __init__(
        self,
        *,
        transcodedVideoIds: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["transcodedVideoIds", b"transcodedVideoIds"]) -> None: ...

global___VideoTranscodeResponse = VideoTranscodeResponse

@typing_extensions.final
class VideoPlaybackRequest(google.protobuf.message.Message):
    """视频播放请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEOID_FIELD_NUMBER: builtins.int
    videoId: builtins.str
    """其他字段..."""
    def __init__(
        self,
        *,
        videoId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["videoId", b"videoId"]) -> None: ...

global___VideoPlaybackRequest = VideoPlaybackRequest

@typing_extensions.final
class VideoPlaybackResponse(google.protobuf.message.Message):
    """视频播放响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYBACKURL_FIELD_NUMBER: builtins.int
    playbackUrl: builtins.str
    """其他字段..."""
    def __init__(
        self,
        *,
        playbackUrl: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["playbackUrl", b"playbackUrl"]) -> None: ...

global___VideoPlaybackResponse = VideoPlaybackResponse

@typing_extensions.final
class VideoScreenshotRequest(google.protobuf.message.Message):
    """视频截图请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEOID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    videoId: builtins.str
    timestamp: builtins.float
    """其他字段..."""
    def __init__(
        self,
        *,
        videoId: builtins.str = ...,
        timestamp: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp", "videoId", b"videoId"]) -> None: ...

global___VideoScreenshotRequest = VideoScreenshotRequest

@typing_extensions.final
class VideoScreenshotResponse(google.protobuf.message.Message):
    """视频截图响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCREENSHOTURL_FIELD_NUMBER: builtins.int
    screenshotUrl: builtins.str
    """其他字段..."""
    def __init__(
        self,
        *,
        screenshotUrl: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["screenshotUrl", b"screenshotUrl"]) -> None: ...

global___VideoScreenshotResponse = VideoScreenshotResponse
