apiVersion: v1
kind: Namespace
metadata:
  name: morphix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  namespace: morphix
  labels:
    app: otelcol
spec:
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
        sidecar.istio.io/inject: "false"
      annotations:
        # checksum/config: 43d3318bb84ce994167ce160b46e0e06eb17a17b8de61b578bf4a3e97f4dcdd1
        morphix: "true"
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
    spec:
      # serviceAccountName: prometheus
      containers:
        - name: otelcol
          # securityContext:
          #   runAsUser: 0 # 指定以 root 用户身份运行容器
          image: otel/opentelemetry-collector-contrib:0.76.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: jaeger-compact
              containerPort: 6831
              protocol: UDP
            - name: jaeger-grpc
              containerPort: 14250
              protocol: TCP
            - name: jaeger-thrift
              containerPort: 14268
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: prometheus
              containerPort: 9464
              protocol: TCP
            - name: zipkin
              containerPort: 9411
              protocol: TCP
          args:
            - --config=/etc/config/otelcol-config.yml
            - --config=/etc/config/otelcol-config-extras.yml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          # env:
          #   - name: MY_POD_IP
          #     valueFrom:
          #       fieldRef:
          #         apiVersion: v1
          #         fieldPath: status.podIP
      volumes:
        - name: config-volume
          configMap:
            name: otelcol

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol
  namespace: morphix
  labels:
    app: otelcol
data:
  otelcol-config-extras.yml: |
    {}
  otelcol-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      otlp:
        endpoint: "jaeger.morphix:4317"
        tls:
          insecure: true
      logging:
      prometheus:
        endpoint: "0.0.0.0:9464"
        resource_to_telemetry_conversion:
          enabled: true
        enable_open_metrics: true

    processors:
      batch:
      filter:
        metrics:
          exclude:
            match_type: strict
            metric_names:
              - queueSize

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        dimensions_cache_size: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
        metrics_flush_interval: 15s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [filter, batch]
          exporters: [prometheus, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

---
apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: morphix
spec:
  selector:
    app: otelcol
  type: ClusterIP
  ports:
    - name: jaeger-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: jaeger-thrift
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: prometheus
      port: 9464
      targetPort: 9464
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
