// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/ydssx/morphix/app/job/internal/common"
	"github.com/ydssx/morphix/app/job/internal/server"
	"github.com/ydssx/morphix/app/job/internal/service"
	"github.com/ydssx/morphix/common/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	jobServer := server.NewJobServer(bootstrap)
	client := common.NewAsynqClient(bootstrap)
	jobService := service.NewJobService(client)
	grpcServer := server.NewGRPCServer(bootstrap, jobService)
	app := newApp(jobServer, grpcServer, bootstrap)
	return app, func() {
	}, nil
}
